package com.example.jotjot.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 / Material You Baseline Colors (Blue/Indigo Palette)
// These will be used as fallback when Dynamic Color is not available (Android < 12)

// Light Theme
val md_theme_light_primary = Color(0xFF415F91)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3E)
val md_theme_light_secondary = Color(0xFF565F71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDAE2F9)
val md_theme_light_onSecondaryContainer = Color(0xFF131C2C)
val md_theme_light_tertiary = Color(0xFF705575)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFAD8FD)
val md_theme_light_onTertiaryContainer = Color(0xFF28132E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_background = Color(0xFFF9F9FF)
val md_theme_light_onBackground = Color(0xFF191C20)
val md_theme_light_surface = Color(0xFFF9F9FF)
val md_theme_light_onSurface = Color(0xFF191C20)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F7)
val md_theme_light_inverseSurface = Color(0xFF2E3036)
val md_theme_light_inversePrimary = Color(0xFFAAC7FF)
val md_theme_light_surfaceTint = Color(0xFF415F91)
val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
val md_theme_light_scrim = Color(0xFF000000)

// New M3 Surface Roles (Light)
val md_theme_light_surfaceDim = Color(0xFFD9D9E0)
val md_theme_light_surfaceBright = Color(0xFFF9F9FF)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF3F3FA)
val md_theme_light_surfaceContainer = Color(0xFFEDEDF4)
val md_theme_light_surfaceContainerHigh = Color(0xFFE7E8EE)
val md_theme_light_surfaceContainerHighest = Color(0xFFE2E2E9)

// Dark Theme
val md_theme_dark_primary = Color(0xFFAAC7FF)
val md_theme_dark_onPrimary = Color(0xFF0A305F)
val md_theme_dark_primaryContainer = Color(0xFF284777)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_secondary = Color(0xFFBEC6DC)
val md_theme_dark_onSecondary = Color(0xFF283141)
val md_theme_dark_secondaryContainer = Color(0xFF3E4759)
val md_theme_dark_onSecondaryContainer = Color(0xFFDAE2F9)
val md_theme_dark_tertiary = Color(0xFFDDBCE0)
val md_theme_dark_onTertiary = Color(0xFF3F2844)
val md_theme_dark_tertiaryContainer = Color(0xFF573E5C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFAD8FD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_background = Color(0xFF111318)
val md_theme_dark_onBackground = Color(0xFFE2E2E9)
val md_theme_dark_surface = Color(0xFF111318)
val md_theme_dark_onSurface = Color(0xFFE2E2E9)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_inverseOnSurface = Color(0xFF111318)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E9)
val md_theme_dark_inversePrimary = Color(0xFF415F91)
val md_theme_dark_surfaceTint = Color(0xFFAAC7FF)
val md_theme_dark_outlineVariant = Color(0xFF44474E)
val md_theme_dark_scrim = Color(0xFF000000)

// New M3 Surface Roles (Dark)
val md_theme_dark_surfaceDim = Color(0xFF111318)
val md_theme_dark_surfaceBright = Color(0xFF37393E)
val md_theme_dark_surfaceContainerLowest = Color(0xFF0C0E13)
val md_theme_dark_surfaceContainerLow = Color(0xFF191C20)
val md_theme_dark_surfaceContainer = Color(0xFF1D2024)
val md_theme_dark_surfaceContainerHigh = Color(0xFF282A2F)
val md_theme_dark_surfaceContainerHighest = Color(0xFF33353A)
